### ISSUE TITLE
Executable not running - macOS

### ISSUE THREAD

**Issue by thatc0der** [CedArctic/digiQuack#1]
I am currently trying to download this tool so that I can convert my ducky scripts to digispark. I am on a Mac and when I try the executable I get this 

/Users/Path/to/digispark/executable
cannot execute binary file
logout

**Comment by CedArctic** [comment]
Did you try using:
sh /path/to/executable 

or

cd /directory/of/executable
chmod +x executable
./executable

?

**Comment by thatc0der** [comment]
I tried to first one. I cd/path/to/executable/ 
sh executable.

**Comment by thatc0der** [comment]
![screen shot 2017-10-07 at 11 29 13 am](https://user-images.githubusercontent.com/14795922/31309350-f8513314-ab52-11e7-93a2-630d65aaa333.png)

I click on the Unix on my mac and this gets printed.

**Comment by CedArctic** [comment]
Try this:
Rename the executable to just digiquack
chmod +x digiquack
./digiquack

Sorry I can't test this myself as I am away from my mac computer at the time being.

**Comment by thatc0der** [comment]
I just tried that and I got this. Still no luck
![screen shot 2017-10-09 at 12 25 35 am](https://user-images.githubusercontent.com/14795922/31325218-88f487dc-ac88-11e7-86d1-b5bd1c11e878.png)

**Comment by thatc0der** [comment]
It still isn't working.

**Comment by CedArctic** [comment]
Download and try the new release. Note that with the new release (1.2.1) for macOS the converted script will be located in your user folder (/Users/yourUserName).

**Comment by thatc0der** [comment]
The script is working now. :)  Question though. If the script doesn't convert and it says something like `Illegal instruction: 4` log out. Does that mean in line 4 in the script I passed that it has an error?

**Comment by CedArctic** [comment]
Don't know actually, I didn't code the specific error message into the program. Possibly means that the script you're trying to convert has something wrong with it. Keep in mind that the program converts a TXT file with the script commands to another TXT file with digispark commands. Don't try converting compiled Ducky payloads using this program, it won't work. Since the binary runs now I'm closing the issue, thanks for pointing it out :)
