### ISSUE TITLE
unterminated argument list invoking macro "F"

### ISSUE THREAD

**Issue by ghost** [CedArctic/digiQuack#3]
**Hi, Im new to all this, and I wanted to convert a rick roll script for the rubber ducky to the digispark, this is the code of the rubber ducky:**
`DELAY 3500
GUI r
DELAY 200
STRING cmd
ENTER
DELAY 200
STRING cd %tmp% && copy con rickyou.vbs
ENTER
STRING While true
ENTER
STRING Dim oPlayer
ENTER
STRING Set oPlayer = CreateObject("WMPlayer.OCX")
ENTER
STRING oPlayer.URL = "https://pixelcoding.nl/download/rickroll.mp3"
ENTER
STRING oPlayer.controls.play
ENTER
STRING While oPlayer.playState <> 1 ' 1 = Stopped
ENTER
STRING WScript.Sleep 100
ENTER
STRING Wend
ENTER
STRING oPlayer.close
ENTER
STRING Wend
ENTER
DELAY 100
CTRL z
ENTER
STRING copy con volup.vbs
ENTER
STRING do
ENTER
STRING Set WshShell = CreateObject("WScript.Shell")
ENTER
STRING WshShell.SendKeys(chr(&hAF))
ENTER
STRING loop
ENTER
CTRL z
ENTER
STRING start rickyou.vbs && volup.vbs`

**And this is the convertion of digiQuack:**
`DigiKeyboard.sendKeyStroke(0);
DigiKeyboard.delay(3500);
DigiKeyboard.sendKeyStroke(0, MOD_GUI_LEFT,KEY_R);
DigiKeyboard.delay(200);
DigiKeyboard.print(F("cmd"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(200);
DigiKeyboard.print(F("cd %tmp% && copy con rickyou.vbs"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("While true"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("Dim oPlayer"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("Set oPlayer = CreateObject("WMPlayer.OCX")"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("oPlayer.URL = "https://pixelcoding.nl/download/rickroll.mp3""));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("oPlayer.controls.play"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("While oPlayer.playState <> 1 ' 1 = Stopped"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("WScript.Sleep 100"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("Wend"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("oPlayer.close"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("Wend"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.sendKeyStroke(MOD_CONTROL_LEFT,KEY_Z);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("copy con volup.vbs"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("do"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("Set WshShell = CreateObject("WScript.Shell")"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("WshShell.SendKeys(chr(&hAF))"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("loop"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.sendKeyStroke(MOD_CONTROL_LEFT,KEY_Z);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.print(F("start rickyou.vbs && volup.vbs"));
for(;;){ /*empty*/ }`

**This is the error I get:**
`Arduino:1.8.5 (Windows 10), Tarjeta:"Digispark (Default - 16.5mhz)"

sketch_mar29a:46: error: unterminated argument list invoking macro "F"

 for(;;){ /*empty*/ }

 ^

exit status 1
unterminated argument list invoking macro "F"`

**Comment by CedArctic** [comment]
This probably refers to lines like these:
DigiKeyboard.print(**F**("WshShell.SendKeys(chr(&hAF))"));
Notice the **bold F** in that line. That tells the Digispark to load the string in the flash memory, that's used for big strings but it can cause problems, try removing some F's and see if it compiles.

**Comment by laughingcypher** [comment]
it isnt compiling any other solution

**Comment by laughingcypher** [comment]
> 
> 
> **Hi, Im new to all this, and I wanted to convert a rick roll script for the rubber ducky to the digispark, this is the code of the rubber ducky:**
> `DELAY 3500 GUI r DELAY 200 STRING cmd ENTER DELAY 200 STRING cd %tmp% && copy con rickyou.vbs ENTER STRING While true ENTER STRING Dim oPlayer ENTER STRING Set oPlayer = CreateObject("WMPlayer.OCX") ENTER STRING oPlayer.URL = "https://pixelcoding.nl/download/rickroll.mp3" ENTER STRING oPlayer.controls.play ENTER STRING While oPlayer.playState <> 1 ' 1 = Stopped ENTER STRING WScript.Sleep 100 ENTER STRING Wend ENTER STRING oPlayer.close ENTER STRING Wend ENTER DELAY 100 CTRL z ENTER STRING copy con volup.vbs ENTER STRING do ENTER STRING Set WshShell = CreateObject("WScript.Shell") ENTER STRING WshShell.SendKeys(chr(&hAF)) ENTER STRING loop ENTER CTRL z ENTER STRING start rickyou.vbs && volup.vbs`
> 
> **And this is the convertion of digiQuack:**
> `DigiKeyboard.sendKeyStroke(0); DigiKeyboard.delay(3500); DigiKeyboard.sendKeyStroke(0, MOD_GUI_LEFT,KEY_R); DigiKeyboard.delay(200); DigiKeyboard.print(F("cmd")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.delay(200); DigiKeyboard.print(F("cd %tmp% && copy con rickyou.vbs")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("While true")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("Dim oPlayer")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("Set oPlayer = CreateObject("WMPlayer.OCX")")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("oPlayer.URL = "https://pixelcoding.nl/download/rickroll.mp3"")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("oPlayer.controls.play")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("While oPlayer.playState <> 1 ' 1 = Stopped")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("WScript.Sleep 100")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("Wend")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("oPlayer.close")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("Wend")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.delay(100); DigiKeyboard.sendKeyStroke(MOD_CONTROL_LEFT,KEY_Z); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("copy con volup.vbs")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("do")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("Set WshShell = CreateObject("WScript.Shell")")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("WshShell.SendKeys(chr(&hAF))")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("loop")); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.sendKeyStroke(MOD_CONTROL_LEFT,KEY_Z); DigiKeyboard.sendKeyStroke(KEY_ENTER); DigiKeyboard.print(F("start rickyou.vbs && volup.vbs")); for(;;){ /*empty*/ }`
> 
> **This is the error I get:**
> `Arduino:1.8.5 (Windows 10), Tarjeta:"Digispark (Default - 16.5mhz)"
> 
> sketch_mar29a:46: error: unterminated argument list invoking macro "F"
> 
> for(;;){ /_empty_/ }
> 
> ^
> 
> exit status 1
> unterminated argument list invoking macro "F"`

did you get any solution ?
