### ISSUE TITLE
The program terminates upon entering the file path

### ISSUE THREAD

**Issue by TheMrRandomDude** [CedArctic/digiQuack#8]
Hello!

I'm using the latest version of the script, md5hash - 39554A9BEA810EEF626EB28E38A18826

Whenever I run the digiQuack.exe and give it the path, it just terminates without any errors (the window closes) and the converted.txt file isn't generated. I tried encoding the .txt file with ANSI, Unicode and UTF-8, no difference. I tried running the .exe in different compatibility modes in windows, it didn't work.

I'm currently using Windows 10 64 bit.

**EDIT:** It works fine on Linux by the way, so there's no huge need to fix it for Windows :)

**Comment by garetalban** [comment]
I ran into this issue as well. It seems when the source file to be converted is not in the same directory as the digiQuak.exe file it fails, and the application closes.
I moved the .txt file into the downloads folder where the digiQuak.exe was extracted to and the conversion file was generated in the downloads folder. 
I just used this for the first time so working out some kinks too.

**Comment by CedArctic** [comment]
Sorry guys for the late reply, I just managed to see this. Glad everything is working well on linux. On Windows I just drag and drop the txt file into the command prompt and everything seems to be working OK. In the mean time I'm closing the issue but do feel free to report any other findings and I can re-open it.

**Comment by 5k4r5** [comment]
I have the same problem. I also did what garetalban said but it didn't work. I tried reinstalling it, but it also didn't work. It would be great if you could help me.
