### ISSUE TITLE
Issues with " and \ characters

### ISSUE THREAD

**Issue by bwees** [CedArctic/digiQuack#9]
The quote and forward slash charachters do not translate correctly. If the converter finds either one of those, it needs to be doubled up (ie. " becomes "" and / becomes //)

**Comment by CedArctic** [comment]
@bwees Are you using digiQuack online or locally (the C++ version)?

**Comment by bwees** [comment]
I am using it online via the javascript version

**Comment by CedArctic** [comment]
@bwees So looking into things, I've spotted the following issues:
- Backslashes need to be escaped ( \ -> \ \ ) when converted
- Double-quotes need to be escaped as well (" -> \\")

However I do not see the issue with forward slashes which seems to convert correctly. Inserting double quotes would result in a syntactically invalid string, I believe it needs to be escaped as mentioned above.

Currently the following translate like this:
- Forward slash:    STRING Hell/o    ->    DigiKeyboard.print("Hell/o"); :heavy_check_mark: 
- Back slash:    STRING Hell\o    ->    DigiKeyboard.print("Hell\o"); :x:     -> Needs to be DigiKeyboard.print("Hell\ \o");
- Double-quotes:    STRING Hell"o    ->    DigiKeyboard.print("Hell"o"); :x:     -> Needs to be DigiKeyboard.print("Hell\ "o");

Let me know if I am missing something and I'll work on the necessary fixes asap. Thanks for finding these bugs! :+1:

**Comment by bwees** [comment]
What you have explained is correct. I literally just looked at my code and it was backslashes. 🤦 

However Double quotes need to be like DigiKeyboard.print("Hell""o");

**Comment by CedArctic** [comment]
@bwees Github originally made my above comment lose its escaped characters, I have updated it with a space to make it clearer. What you wrote above will probably cause a compiler error if I am not mistaken, since you have non-escaped double quotes.

**Comment by CedArctic** [comment]
@bwees I've pushed fixes for what we discussed above. If you believe that there is something that has escaped us feel free to comment here and I will re-open the issue. Thanks for helping spot these issues! :+1:

**Comment by bwees** [comment]
No problem! Here is the source for the double quotes:
https://forum.arduino.cc/index.php?topic=41872.0

**Comment by CedArctic** [comment]
The thread linked concludes to what I mentioned about character escaping above. The fixes I pushed earlier cover these and everything should work as expected now.

**Comment by bwees** [comment]
👍
